
import java.util.HashSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *1 inicio botones deshabilitados (set.Enabled)
 * 2 boton para habilitar botones
 * 3 boton para deshabilitar
 * 4 agregar boton con X
 * 5 botn reset
 * 
 * @author jose.zapatagom
 */
public class Tateti extends javax.swing.JFrame {

    /**
     * Creates new form Tateti
     */
    public Tateti() {
        initComponents();
        x1.setEnabled(false);
        x2.setEnabled(false);
        x3.setEnabled(false);
        x4.setEnabled(false);
        x5.setEnabled(false);
        x6.setEnabled(false);
        x7.setEnabled(false);
        x8.setEnabled(false);
        x9.setEnabled(false);
        op1juan.setEnabled(false);
        op2pedro.setEnabled(false);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        op1juan = new javax.swing.JRadioButton();
        op2pedro = new javax.swing.JRadioButton();
        x2 = new javax.swing.JButton();
        x3 = new javax.swing.JButton();
        x4 = new javax.swing.JButton();
        x1 = new javax.swing.JButton();
        x5 = new javax.swing.JButton();
        x9 = new javax.swing.JButton();
        x6 = new javax.swing.JButton();
        x7 = new javax.swing.JButton();
        x8 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jugador2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inicio.setText("INICIO");
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });

        stop.setText("STOP");
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopMouseClicked(evt);
            }
        });

        op1juan.setText("Juan");
        op1juan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op1juanMouseClicked(evt);
            }
        });

        op2pedro.setText("Pedro");
        op2pedro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op2pedroMouseClicked(evt);
            }
        });

        x2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x2MouseClicked(evt);
            }
        });

        x3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x3MouseClicked(evt);
            }
        });

        x4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x4MouseClicked(evt);
            }
        });

        x1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x1MouseClicked(evt);
            }
        });
        x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1ActionPerformed(evt);
            }
        });

        x5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x5MouseClicked(evt);
            }
        });

        x9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x9MouseClicked(evt);
            }
        });

        x6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x6MouseClicked(evt);
            }
        });
        x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x6ActionPerformed(evt);
            }
        });

        x7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x7MouseClicked(evt);
            }
        });

        x8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x8MouseClicked(evt);
            }
        });

        reset.setText("RESET");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });

        jugador2.setText("JUGADOR");
        jugador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugador2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(x7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(x8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(x9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(op1juan)
                                .addGap(18, 18, 18)
                                .addComponent(op2pedro)
                                .addGap(30, 30, 30)
                                .addComponent(reset))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jugador2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(inicio)
                        .addGap(69, 69, 69)
                        .addComponent(stop)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicio)
                    .addComponent(stop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jugador2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op1juan)
                    .addComponent(op2pedro)
                    .addComponent(reset))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x6ActionPerformed

    private void x2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x2MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x2.setText("X");
           if(x2.getText()=="X"){
           x2.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           
           }
       }
       else{
           x2.setText("0");
           x2.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       }  
        
       
    }//GEN-LAST:event_x2MouseClicked

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
        // TODO add your handling code here:
        x1.setEnabled(true);
        x2.setEnabled(true);
        x3.setEnabled(true);
        x4.setEnabled(true);
        x5.setEnabled(true);
        x6.setEnabled(true);
        x7.setEnabled(true);
        x8.setEnabled(true);
        x9.setEnabled(true);
        op1juan.setEnabled(true);
        op2pedro.setEnabled(true);
        op2pedro.setSelected(false);
        op1juan.setSelected(true);
    }//GEN-LAST:event_inicioMouseClicked

    private void stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseClicked
        // TODO add your handling code here:
        x1.setEnabled(false);
        x2.setEnabled(false);
        x3.setEnabled(false);
        x4.setEnabled(false);
        x5.setEnabled(false);
        x6.setEnabled(false);
        x7.setEnabled(false);
        x8.setEnabled(false);
        x9.setEnabled(false);
        op1juan.setEnabled(false);
        op2pedro.setEnabled(false);
    }//GEN-LAST:event_stopMouseClicked

    private void x1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x1MouseClicked
        // TODO add your handling code here:
               
        if (op1juan.isSelected()==true){
            x1.setText("X");
            if(x1.getText()=="X"){
            x1.setEnabled(false);
            op1juan.setSelected(false);
            op2pedro.setSelected(true);
            }
        }
        else{
            x1.setText("0");
            x1.setEnabled(false);  
            op1juan.setSelected(true);
            op2pedro.setSelected(false);
        }    
    }//GEN-LAST:event_x1MouseClicked

    private void x3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x3MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
            x3.setText("X");
            if(x3.getText()=="X"){
            x3.setEnabled(false);
            op1juan.setSelected(false);
            op2pedro.setSelected(true);
            }
        }
        else{
            x3.setText("0");
            x3.setEnabled(false);  
            op1juan.setSelected(true);
            op2pedro.setSelected(false);
        } 
       
    }//GEN-LAST:event_x3MouseClicked

    private void x4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x4MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x4.setText("X");
           if(x4.getText()=="X"){
           x4.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x4.setText("0");
           x4.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
       
    }//GEN-LAST:event_x4MouseClicked

    private void x5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x5MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x5.setText("X");
           if(x5.getText()=="X"){
           x5.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x5.setText("0");
           x5.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
        
    }//GEN-LAST:event_x5MouseClicked

    private void x6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x6MouseClicked
        // TODO add your handling code here:
      if (op1juan.isSelected()==true){
           x6.setText("X");
           if(x6.getText()=="X"){
           x6.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x6.setText("0");
           x6.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
       
    }//GEN-LAST:event_x6MouseClicked

    private void x7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x7MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x7.setText("X");
           if(x7.getText()=="X"){
           x7.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x7.setText("0");
           x7.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
        
    }//GEN-LAST:event_x7MouseClicked

    private void x8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x8MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x8.setText("X");
           if(x8.getText()=="X"){
           x8.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x8.setText("0");
           x8.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
    }//GEN-LAST:event_x8MouseClicked

    private void x9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x9MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x9.setText("X");
           if(x9.getText()=="X"){
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           x9.setEnabled(false);
           }
       }
       else{
           x9.setText("0");  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
           x9.setEnabled(false);
       } 
    }//GEN-LAST:event_x9MouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        // TODO add your handling code here:
        
        x1.setText("");
        x2.setText("");
        x3.setText("");
        x4.setText("");
        x5.setText("");
        x6.setText("");
        x7.setText("");
        x8.setText("");
        x9.setText("");
    }//GEN-LAST:event_resetMouseClicked

    private void jugador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugador2MouseClicked
        // TODO add your handling code here:
          
    op1juan.setSelected(false);
    op2pedro.setSelected(true);
    }//GEN-LAST:event_jugador2MouseClicked

    private void op1juanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op1juanMouseClicked
        // TODO add your handling code here:
        op1juan.setSelected(true);
        op2pedro.setSelected(false);
        
    }//GEN-LAST:event_op1juanMouseClicked

    private void op2pedroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op2pedroMouseClicked
        // TODO add your handling code here:
        op1juan.setSelected(false);
        op2pedro.setSelected(true);
    }//GEN-LAST:event_op2pedroMouseClicked

    private void x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_x1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tateti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tateti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tateti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tateti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tateti().setVisible(true);
            }
        });
        
        
     String [][] tablero =new String [3][3] ;
     int i=0;
     int ii=0;
     
     
     
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inicio;
    private javax.swing.JButton jugador2;
    private javax.swing.JRadioButton op1juan;
    private javax.swing.JRadioButton op2pedro;
    private javax.swing.JButton reset;
    private javax.swing.JButton stop;
    private javax.swing.JButton x1;
    private javax.swing.JButton x2;
    private javax.swing.JButton x3;
    private javax.swing.JButton x4;
    private javax.swing.JButton x5;
    private javax.swing.JButton x6;
    private javax.swing.JButton x7;
    private javax.swing.JButton x8;
    private javax.swing.JButton x9;
    // End of variables declaration//GEN-END:variables
}
